### ISSUE TITLE
Files / Chapters > the 0th file, display blank on Kobo, Nook and Readman ereaders 

### ISSUE THREAD

**Issue by KenH2000** [kevinboone/txt2epub#2]
When I create an epub with chapters, the book displays in Calibre's reader normally, but in ereaders (tested in Kobo, Nook, & Readman) any chapter > 1st file only shows a blank page. Turning to the next page causes the ereader to jump several pages (to the next chapter apparently), and then again only displays a blank page.

I've created a sample_chap_error.epub file in my fork, in the tests folder.

**Comment by KenH2000** [comment]
I was able to correct the 'blank chapters' problem by feeding the txt2epub generated epub file into calibre ebook editor and running the 'bug check' then 'try to fix all errors', then saving the fixed epub.  The book works perfect in Kobo now with fully functioning TOC.  

Calibre changed:
1.  The quotes in 1st line (xml definition lines) in html files -- probably not significant
2.  The toc.ncx file -- Bang!  I think this is our smoking gun
3.  The zip format -- probably not significant

I don't know what it did to the zip file.  The archive manager GUI throws an error trying to open, where unzip from the command line succeeds.  

I think changing the TOC to Calibre's style would fix the bug.

More details:

Calibre changed the quotes in 1st xml line in html files:
```
        from <?xml version="1.0" encoding="utf-8"?>  
        to     <?xml version='1.0' encoding='utf-8'?>
```
and it changed the TOC to this:
```
     <?xml version='1.0' encoding='utf-8'?>
     <ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1" xml:lang="en">
    <head>
      <meta name="dtb:uid" content="isbn"/>
     <meta name="dtb:depth" content="2"/>
     <meta name="dtb:generator" content="calibre (5.44.0)"/>
     <meta name="dtb:totalPageCount" content="0"/>
     <meta name="dtb:maxPageNumber" content="0"/>
    </head>
    <docTitle>
     <text>sample</text>
     </docTitle>
    <navMap>
     <navPoint id="num_1" playOrder="1">
      <navLabel>
        <text>chapter00</text>
      </navLabel>
      <content src="file0.html"/>
    </navPoint>
    <navPoint id="num_2" playOrder="2">
      <navLabel>
        <text>chapter01</text>
      </navLabel>
      <content src="file1.html"/>
     </navPoint>
     <navPoint id="num_3" playOrder="3">
      <navLabel>
        <text>chapter03</text>
      </navLabel>
      <content src="file2.html"/>
     </navPoint>
     </navMap>
     </ncx>
```

**Comment by KenH2000** [comment]
OK, I changed the TOC to the calibre style (updated epub.c posted in 'tests' folder) -- that did not clear the bug.  The txt2epub program is adding some paragraph tags in files > 0 (file1.html, file2.html, etc) in the wrong place.  Deleting the errant tags cleared the bug.
```
...
     <body> 
     <p>                                  <--DELETE P TAG HERE
     <h1></p><p>CHAPTER 1</h1>            <--DELETE P TAGS HERE
     </p><p><br/>                         <--DELETE /P TAG HERE
    </p><p>ELIZABETH Present Day - Friday Evening
    </p><p><br/>
    </p><p>Squinting at the dashboard clock, Elizabeth
...
```

**Comment by kevinboone** [comment]
So, you're assessment is that this isn't a problem with the table of contents, but with formatting in general? The sample HTML output you posted has the `<h1>` tag squeezed between beginning and ending paragraphs, which is obviously wrong.

But I still can't reproduce this problem myself, with text files I create. Could you supply some text that I can use to follow up? I've no doubt it's a bug on my part, but it's going to be fiddly to fix if I can't reproduce it.

**Comment by KenH2000** [comment]
Sorry I should have thought of that.  I posted the files I used (chapter00.txt, chapter01.txt, and chapter03.txt) in the 'tests' folder (I inadvertently left out chapter02.txt).
The command I ran was:
```
txt2epub -a sample -t sample -f -o sample_book_nofix.epub chapter00.txt chapter01.txt chapter03.txt
```
At chapters 1 and 3, it produced the errors discussed above.

**Comment by kevinboone** [comment]
I think this problem arises when a chapter heading (i.e., first line of a text file) starts with spaces. There's something about this combination -- first line, and space indentation -- that screws up txt2epub's parser. It ends up writing `<p><h1></p>title</h1>`, which is clearly wrong. 

I will look into this. Please bear with me.

**Comment by kevinboone** [comment]
Please try the latest upload. To be honest, it's a dirty fix, and I'm not sure whether it will handle all possible oddities. If I had time, I would re-do the parsing logic completely -- it's really not something I'm proud of. Unfortunately, I don't really have time :/

**Comment by KenH2000** [comment]
The updated text.h, text.c, and main.c files corrected the bug on my test book.  I ran txt2epub on the entire book of 57 chapters, and was able to navigate to every chapter with no issues on the Kobo reader.

**Comment by kevinboone** [comment]
OK. Thanks for the feedback. Please let me if it turns out that I haven't fixed it properly ;)

**Comment by kevinboone** [comment]
Since I haven't heard anything for over a year, I'm assuming that this is no longer a problem.
